prebuilt: a2sd and dependecies
also add htop,powertop,terminfo (for AndroidTerm)

Change-Id: I3dbda59381d30538291e354b4ec8c22e0fb950b5

diff --git a/prebuilt/common/etc/init.d/05mountext b/prebuilt/common/etc/init.d/05mountext
--- a/prebuilt/common/etc/init.d/05mountext
+++ b/prebuilt/common/etc/init.d/05mountext
@@ -1,46 +1,51 @@
 #!/system/bin/sh
 #
 # mount ext partition from sd card
-
-BB="logwrapper busybox";
+# Revised 20111220 by Andrew Sutherland for apps2sd on Evervolv ICS
 
 if [ "$SD_EXT_DIRECTORY" = "" ];
 then
     SD_EXT_DIRECTORY=/sd-ext;
 fi;
+BB="/system/xbin/busybox";
+FDISK="$BB fdisk -l";
+E2FSCK="/system/bin/e2fsck";
 
 # find SD Card
 for MMC_NUM in `seq 0 9`;
 do
-    MMC_TYPE=`cat /sys/block/mmcblk$MMC_NUM/device/type`
+    MMC_TYPE=`cat /sys/block/mmcblk${MMC_NUM}/device/type`
     if [ "$MMC_TYPE" = "SD" ];
     then
         # 2nd partition of sdcard should be the sd-ext if it exists
         SD_EXT_PART=/dev/block/mmcblk${MMC_NUM}p2
-        break
-    fi
+        # Find the linux and swap partitions (if they exist)
+        #SD_EXT_PART=`$FDISK /dev/block/mmcblk${MMC_NUM} | awk '/^\// && $5 == 83 {print $1;exit;}'`;
+        SWAP_PART=`$FDISK /dev/block/mmcblk${MMC_NUM} | awk '/^\// && $5 == 82 {print $1;exit;}'`;
+        setprop ev.sdextpart $SD_EXT_PART
+        break;
+    fi;
 done
-
+# mount sdcard if a valid partition was found
 if [ -b "$SD_EXT_PART" ];
 then
-    log -p i -t mountext "Checking partition for errors...";
-
+    log -p i -t mountext "Checking $SD_EXT_PART for errors...";
     # fsck the sd-ext filesystem first
-    if [ -x `which e2fsck` ];
+    if [ -x "$E2FSCK" ];
     then
-        e2fsck -y $SD_EXT_PART
-        e2fsk_exitcode=$?
+        $E2FSCK -y $SD_EXT_PART;
+        e2fsk_exitcode=$?;
     else
-        log -p i -t mountext "executable e2fsck not found, assuming no filesystem errors"
-        e2fsk_exitcode=0
-    fi
-
+        log -p i -t mountext "executable e2fsck not found, assuming no filesystem errors";
+        e2fsk_exitcode=0;
+    fi;
     # set property with exit code in case an error occurs
     setprop ev.e2fsck.errors $e2fsk_exitcode;
     if [ "$e2fsk_exitcode" -lt 2 ];
     then
         # mount and set perms
-        $BB mount -o rw,noatime,nodiratime,barrier=1 $SD_EXT_PART $SD_EXT_DIRECTORY;
+        # it is ok to mount ext[3/4] partitions as ext4
+        $BB mount -t ext4 -o noauto_da_alloc,data=ordered,commit=15,barrier=1,nouser_xattr,errors=continue,noatime,nodiratime,nosuid,nodev $SD_EXT_PART $SD_EXT_DIRECTORY;
         if [ "$?" = 0 ];
         then
             $BB chown 1000:1000 $SD_EXT_DIRECTORY;
@@ -48,8 +53,23 @@ then
             log -p i -t mountext "$SD_EXT_DIRECTORY successfully mounted";
         else
             log -p e -t mountext "Unable to mount filesystem for $SD_EXT_DIRECTORY!";
-        fi
+        fi;
     else
+        log -p e -t mountext "e2fsck returned error $e2fsk_exitcode";
         log -p e -t mountext "Unable to repair ext partition...not mounting";
-    fi
-fi
+    fi;
+else
+    log -p e -t mountext "linux partition not found on sdcard";
+fi;
+# enable swap
+if [ "$SWAP_PART" = "" ];
+then
+    setprop ev.swap 0;
+    setprop ev.swappart "none";
+    log -p i -t mountext "No swap partition found.";
+else
+    $BB swapon $SWAP_PART;
+    setprop ev.swap 1;
+    setprop ev.swappart $SWAP_PART;
+    log -p i -t mountext "Swap enabled on $SWAP_PART";
+fi;
