Bring back squisher
Some devices could benefit from the size reduction from running
squisher, so bring back a revised version as an optional part of the
build process.

This version of squisher no longer handles the process of making
release OTAs, instead operating on $OUT/system before system images and
OTAs are created.  This has the advantage of avoiding having to unzip a
just-packed OTA to optimize it before repacking it.

Change-Id: I288f694fd1bf26782e05dcfa797a0569d9fdf9cb

diff --git a/tools/squisher b/tools/squisher
--- a/tools/squisher
+++ b/tools/squisher
@@ -1,108 +1,41 @@
-#!/bin/sh
+#!/bin/bash
 #
 # Squish a CM otapackage for distribution
 # cyanogen
 #
 
-OUT_TARGET_HOST=`uname -a | grep Darwin`
-if [ -z "$OUT_TARGET_HOST" ]
+. $ANDROID_BUILD_TOP/vendor/cm/tools/functions
+
+OUT_TARGET_HOST=`uname -s`
+if [ x"$OUT_TARGET_HOST" = x"Linux" ]
 then
    OUT_TARGET_HOST=linux-x86
-   MD5=md5sum
    XARGS="xargs --max-args=1 --max-procs `grep 'processor' /proc/cpuinfo|wc -l`"
-   SED=sed
-else
+elif [ x"$OUT_TARGET_HOST" = x"Darwin" ]
+then
    OUT_TARGET_HOST=darwin-x86
-   MD5=md5
    XARGS="xargs -n 1 -P `sysctl hw.ncpu | awk '{print $2}'`"
-   SED=gsed
+else
+   echo -e $CL_RED"ERROR: unknown/unsupported host OS!"$CL_RST
+   exit 1
 fi
 
 if [ -z "$OUT" -o ! -d "$OUT" ]; then
-	echo "ERROR: $0 only works with a full build environment. $OUT should exist."
+	echo -e $CL_RED"ERROR: $0 only works with a full build environment. $OUT should exist."$CL_RST
 	exit 1
 fi
 
-ROMVERSION=$1
-MODVERSION=$ROMVERSION-squished
-
-OTAPACKAGE=$OUT/$ROMVERSION.zip
-if [ ! -f "$OTAPACKAGE" ]; then
-	echo "$OTAPACKAGE doesn't exist!";
-	exit 1
-fi
-
-OPTICHARGER=$ANDROID_BUILD_TOP/vendor/ev/tools/opticharger
+OPTICHARGER="$ANDROID_BUILD_TOP"/vendor/cm/tools/opticharger
 QUIET=-q
 DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"
 
-REPACK=$OUT/repack.d
-printf "Sanitizing environment..."
-rm -rf $REPACK
-mkdir -p $REPACK
-echo
-
-
-# Unpack the otapackage and opticharge all apks
-mkdir $REPACK/ota
-(
-cd $REPACK/ota
-printf "Unpacking $OTAPACKAGE..."
-unzip $QUIET $OTAPACKAGE
-echo
-cd $REPACK/ota/system/framework
-$OPTICHARGER framework-res.apk
-cd $REPACK/ota/system/app
-find ./ -name \*.apk | $XARGS $OPTICHARGER
-cd $REPACK/ota/system/priv-app
-find ./ -name \*.apk | $XARGS $OPTICHARGER
-)
-
-# Fix build.prop
-$SED -i \
-	-e '/ro\.build\.romversion/s/$/-squished/' \
-	$REPACK/ota/system/build.prop
-#	-e '/ro\.build\.type/s/eng/user/' \
-
+# Optimize PNG resources in APKs
+( cd "$OUT"/system; find framework/ app/ priv-app/ vendor/app/ -name \*.apk -print | $XARGS "$OPTICHARGER"; )
 
 # Delete unnecessary binaries
-( cd $REPACK/ota/system/bin; echo $DELETE_BINS | xargs rm -f; )
+( cd "$OUT"/system/bin; echo $DELETE_BINS | xargs rm -f; )
 
-# No need for recovery
-rm -rf $REPACK/ota/recovery
-
-# Strip modules
-[ -d $REPACK/ota/system/lib/modules ] && \
-	find $REPACK/ota/system/lib/modules -name "*.ko" -print0 | xargs -0 arm-eabi-strip --strip-unneeded
-
-# Determine what to name the new signed package
-OUTFILE=$OUT/$MODVERSION.zip
-
-# Pack it up and sign
-printf "Zipping package..."
-( cd $REPACK/ota; zip $QUIET -r $REPACK/update.zip . )
-echo
-printf "Signing package..."
-SECURITYDIR=$ANDROID_BUILD_TOP/build/target/product/security
-java -Xmx2048m \
-	-jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar \
-	-w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
-	$REPACK/update.zip $OUTFILE
-echo
-printf "Cleaning up..."
-rm -rf $REPACK
-rm -f $OTAPACKAGE
-echo
-
-# Create a md5 checksum image of the repacked package
-(
-img=`basename $OUTFILE`
-cd `dirname $OUTFILE`
-$MD5 $img >$img.md5sum
-echo
-echo "Package complete: $OUTFILE"
-cat $img.md5sum
-echo
-)
+# We should fix the build to stop this from being installed in the first place
+rm -rf "$OUT"/system/extras
 
 exit 0
